### ISSUE TITLE
Change observation / value checker to be case insensitive

### ISSUE THREAD

**Issue by magp18** [SwissTPH/pyfhirsdc#31]
writing "Stiff Neck" instead of "Stiff neck" will throw an error at CQL level

**Comment by delcroip** [comment]
May be we need to lower all the code

Patrick Delcroix
+41 79 618 69 78
***@***.***
________________________________
De : Marco Pereira ***@***.***>
Envoyé : mardi 11 octobre 2022 16:27
À : SwissTPH/pyfhirsdc
Cc: Subscribed 
Objet : [SwissTPH/pyfhirsdc] Change observation / value checker to be case insensitive (Issue #31)

writing "Stiff Neck" instead of "Stiff neck" will throw an error at CQL level
